first_project/first_app/urls.py
from django.urls import path
from first_app import views


urlpatterns=[
    path('index/',views.index,name='index'),
    path('home/',views.home,name='home'),
    path('static_image/',views.img,name='img')

]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first_app/',include('first_app.urls')),
    path('second_app/',include('second_app.urls'))



]

first_project/second_app/urls.py
from django.urls import path
from second_app.views import index,user,form_detail_view,relative

app_name = 'second_app'
urlpatterns=[
    path('index/',index,name='index'),
    path('users/',user,name='user'),
    path('form_details/',form_detail_view,name='form_details'),
    path('relative/',relative,name='relative')
]

first_project/first_app/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    first_name=models.CharField(max_length=150)
    last_name=models.CharField(max_length=150)
    email_id=models.EmailField(max_length=80,unique=True)

    def __str__(self):
        return self.first_name

first_project/second_app/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    first_name=models.CharField(max_length=150)
    last_name=models.CharField(max_length=150)
    email_id=models.EmailField(max_length=80,unique=True)

    def __str__(self):
        return self.first_name

class details(models.Model):
    add=models.CharField(max_length=200)

    def __str__(self):
        return self.add

first_project/second_app/forms.py
from django import forms
from django.forms.widgets import HiddenInput
from  django.core import validators
from second_app.models import User


class FormDetails(forms.ModelForm):
    class Meta:
        model=User
        fields='__all__'
        #exclude=['first_name']
        #field=['first_name']

#class FormDetails(forms.Form):
  #  first_name=forms.CharField()
 #   last_name=forms.CharField()
  #  email_id=forms.EmailField()
   # verify_email=forms.EmailField()
   # botcatcher=forms.CharField(required=False,widget=HiddenInput,validators=[validators.MaxLengthValidator(0)])


#def clean(self):
  #  get_all=super().clean()
    #if get_all['email_id']!=get_all['verify_email']:
     #   raise forms.ValidationError("email is not matched")

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def index(request):
    a=5+5
    my_dict={'insert_me':'inserted from view','second_key':a}
    return render(request,'first_app/index.html',my_dict)

def home(request):
    return HttpResponse ("WELCOME TO HOME PAGE")

def img(request):
    return render(request,'first_app/static_image.html')

first_project/second_app/views.py
from django.shortcuts import render
from second_app.models import User
from second_app.forms import FormDetails

# Create your views here.
def index(request):
    return render(request,'second_app/index.html')

def user(request):
    userlist=User.objects.order_by('first_name')
    mydict={'user_list': userlist}
    return render(request,'second_app/show_users.html',mydict)

def form_detail_view(request):
    form=FormDetails()
    if request.method =='POST':
        form=FormDetails(request.POST)
        if form.is_valid():
            print(form.cleaned_data['first_name'])
            print(form.cleaned_data['last_name'])
            print(form.cleaned_data['email_id'])
    return render(request,'second_app/form_details.html',{'form':form})

def relative(request):
    return render(request,'second_app/relative_url.html')

first_project/templates/first_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WELCOME</title>
</head>
<body>
<h1>From Index.html</h1>
<h2>{{ insert_me }}</h2>
<h3>{{ second_key }}</h3>
</body>
</html>

first_project/templates/first_app/static_image.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}">
</head>
<body>
<h1>IRON PARADISE</h1>
<img src="{%static "images/DSC_0202.jpg "%}" alt="not found"
</body>
</html>

first_project/templates/second_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>FROM BASE HTML ie base template</h1>
{% block body_block %}


{% endblock %}

</body>
</html>

first_project/templates/second_app/form_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
{{ form.as_p }}
    <input type ="submit" value ="submit">
</form>
</body>
</html>

first_project/templates/second_app/index.html
<!DOCTYPE html>
{% extends 'second_app/base.html' %}
{% block body_block %}
<h1>welcome to index of second app</h1>

{% endblock %}

first_project/templates/second_app/relative_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href ="{% url 'second_app:user' %}">SHOW USER</a>
<a href ="{% url 'second_app:index' %}">GOTO INDEX</a>
<a href ="{% url 'admin:index' %}">ADMIN</a>
<a href ="{% url 'index' %}">INDEX</a>


</body>
</html>

first_project/templates/second_app/show_users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ol>
    {% for user in user_list %}
        <li>USER DETAILS</li>
        <ul>
            <li>First Name:{{user.first_name}}</li>
            <li>Second Name:{{user.second_name }}</li>
            <li>email:{{ user.email_id }}</li>
        </ul>
    {% endfor %}
</ol>

</body>
</html>